#!/bin/bash

###############################################################################
# Phase 2 Skills Test Suite Runner
#
# Runs all Phase 2 skills tests (unit, integration, agent config)
# Generates comprehensive test report
###############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$TEST_DIR/../.." && pwd)"
REPORTS_DIR="$TEST_DIR/reports"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         Phase 2 Skills Test Suite Runner                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Create reports directory
mkdir -p "$REPORTS_DIR"

# Step 1: Run Jest tests (unit + integration + agent configs)
echo -e "${YELLOW}[1/3] Running Jest tests (unit + integration + agent configs)...${NC}"
echo ""

cd "$PROJECT_ROOT"

if npx jest --config="$TEST_DIR/jest.phase2.config.cjs" --coverage; then
  echo -e "${GREEN}✓ Jest tests passed${NC}"
  JEST_EXIT=0
else
  echo -e "${RED}✗ Jest tests failed${NC}"
  JEST_EXIT=1
fi

echo ""

# Step 2: Run Playwright E2E tests
echo -e "${YELLOW}[2/3] Running Playwright E2E validation tests...${NC}"
echo ""

if npx playwright test tests/e2e/phase2-skills-validation.spec.ts --reporter=html --reporter=json; then
  echo -e "${GREEN}✓ Playwright E2E tests passed${NC}"
  PLAYWRIGHT_EXIT=0
else
  echo -e "${RED}✗ Playwright E2E tests failed${NC}"
  PLAYWRIGHT_EXIT=1
fi

echo ""

# Step 3: Generate summary report
echo -e "${YELLOW}[3/3] Generating test summary report...${NC}"
echo ""

SUMMARY_FILE="$REPORTS_DIR/phase2-test-summary.md"

cat > "$SUMMARY_FILE" << EOF
# Phase 2 Skills Test Suite Summary

**Test Run Date:** $(date)

## Test Results

### Jest Tests (Unit + Integration + Agent Configs)
- **Status:** $([ $JEST_EXIT -eq 0 ] && echo "✅ PASSED" || echo "❌ FAILED")
- **Test Files:**
  - phase2-skills.test.ts (Unit tests for 6 skills)
  - phase2-integration.test.ts (Integration tests for SkillsService)
  - phase2-agent-configs.test.ts (Agent configuration tests)

### Playwright E2E Tests
- **Status:** $([ $PLAYWRIGHT_EXIT -eq 0 ] && echo "✅ PASSED" || echo "❌ FAILED")
- **Test File:**
  - phase2-skills-validation.spec.ts (End-to-end validation)

## Coverage Report

Coverage report available at:
- **HTML:** \`coverage/phase2-skills/index.html\`
- **LCOV:** \`coverage/phase2-skills/lcov.info\`

## Test Artifacts

- **Jest HTML Report:** \`tests/skills/reports/phase2-skills-test-report.html\`
- **Jest JUnit XML:** \`tests/skills/reports/phase2-skills-junit.xml\`
- **Playwright Report:** \`playwright-report/index.html\`

## Phase 2 Implementation Summary

### Skills Created (6 total, 3,447 lines)
1. **shared/user-preferences** - User preference management patterns
2. **shared/task-management** - Fibonacci priority system (P0-P8)
3. **shared/productivity-patterns** - Workflow optimization techniques
4. **agent-specific/meeting-prep-agent/meeting-templates** - Meeting templates library
5. **agent-specific/meeting-prep-agent/agenda-frameworks** - Agenda frameworks catalog
6. **agent-specific/meeting-prep-agent/note-taking** - Note-taking systems

### Agent Configs Updated (3 agents, 13 skill references)
1. **meta-agent** - 4 skills (all Phase 1 protected)
2. **personal-todos-agent** - 4 skills (1 Phase 1 + 3 Phase 2)
3. **meeting-prep-agent** - 5 skills (1 Phase 1 + 4 Phase 2)

## Test Execution Status

**Overall Status:** $([ $JEST_EXIT -eq 0 ] && [ $PLAYWRIGHT_EXIT -eq 0 ] && echo "✅ ALL TESTS PASSED" || echo "❌ SOME TESTS FAILED")

### Exit Codes
- Jest: $JEST_EXIT
- Playwright: $PLAYWRIGHT_EXIT
- Combined: $([ $JEST_EXIT -eq 0 ] && [ $PLAYWRIGHT_EXIT -eq 0 ] && echo "0" || echo "1")

---

**Generated by:** Phase 2 Skills Test Suite Runner
**Report Location:** \`$SUMMARY_FILE\`
EOF

echo -e "${GREEN}✓ Summary report generated: $SUMMARY_FILE${NC}"
echo ""

# Display summary
cat "$SUMMARY_FILE"

# Final exit code
if [ $JEST_EXIT -eq 0 ] && [ $PLAYWRIGHT_EXIT -eq 0 ]; then
  echo ""
  echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║            🎉 ALL PHASE 2 TESTS PASSED! 🎉                    ║${NC}"
  echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
  exit 0
else
  echo ""
  echo -e "${RED}╔════════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${RED}║            ❌ SOME PHASE 2 TESTS FAILED                       ║${NC}"
  echo -e "${RED}╚════════════════════════════════════════════════════════════════╝${NC}"
  exit 1
fi
