import { test, expect, Page } from '@playwright/test';
import { ClaudeTerminalPage } from './page-objects/claude-terminal-page';
import { StormSimulator } from './utils/storm-simulator';
import { EscapeSequenceMonitor } from './utils/escape-sequence-monitor';
import { SystemResourceMonitor } from './utils/system-resource-monitor';

test.describe('Escape Sequence Storm Simulation Tests', () => {
  let claudePage: ClaudeTerminalPage;
  let stormSimulator: StormSimulator;
  let escapeMonitor: EscapeSequenceMonitor;
  let resourceMonitor: SystemResourceMonitor;
  
  test.beforeEach(async ({ page }) => {
    claudePage = new ClaudeTerminalPage(page);
    stormSimulator = new StormSimulator(page);
    escapeMonitor = new EscapeSequenceMonitor(page);
    resourceMonitor = new SystemResourceMonitor(page);
    
    await claudePage.navigate();
    await claudePage.waitForPageLoad();
    
    // Start monitoring before simulation
    await escapeMonitor.startMonitoring();
    await resourceMonitor.startMonitoring();
  });

  test.afterEach(async ({ page }) => {
    await escapeMonitor.stopMonitoring();
    await resourceMonitor.stopMonitoring();
    
    // Clean up any remaining processes
    await claudePage.cleanupAllProcesses();
  });

  test('should prevent rapid spawn button storm', async () => {
    // Configure storm simulation
    const stormConfig = {
      type: 'button-spam',
      intensity: 'high',
      duration: 5000, // 5 seconds
      clickInterval: 10 // Every 10ms
    };
    
    // Start storm simulation
    await stormSimulator.startStorm(stormConfig);
    
    // Monitor during storm
    const stormMetrics = await stormSimulator.getStormMetrics();
    expect(stormMetrics.clicksAttempted).toBeGreaterThan(100);
    
    // Verify prevention worked
    const processCount = await claudePage.getActiveProcessCount();
    expect(processCount).toBeLessThanOrEqual(1);
    
    // Verify button debouncing
    const buttonMetrics = await claudePage.getButtonInteractionMetrics();
    expect(buttonMetrics.actualClicks).toBeLessThan(stormMetrics.clicksAttempted);
    expect(buttonMetrics.preventedClicks).toBeGreaterThan(0);
    
    // Verify no escape sequence storm
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.stormDetected).toBe(false);
  });

  test('should handle terminal output flood simulation', async () => {
    await claudePage.clickSpawnButton();
    await claudePage.waitForProcessSpawn();
    
    // Simulate flood of terminal output
    const floodConfig = {
      type: 'output-flood',
      messagesPerSecond: 100,
      duration: 10000, // 10 seconds
      messageLength: 1000
    };
    
    await stormSimulator.simulateOutputFlood(floodConfig);
    
    // Monitor system during flood
    const resourceMetrics = await resourceMonitor.getMetrics();
    expect(resourceMetrics.memoryUsage).toBeLessThan(1024 * 1024 * 1024); // < 1GB
    expect(resourceMetrics.cpuUsage).toBeLessThan(90);
    
    // Verify terminal buffer management
    const terminalMetrics = await claudePage.getTerminalMetrics();
    expect(terminalMetrics.bufferOverflow).toBe(false);
    expect(terminalMetrics.linesDropped).toBeGreaterThan(0); // Buffer limiting working
    
    // Verify UI remains responsive
    const uiResponsive = await claudePage.testUIResponsiveness();
    expect(uiResponsive).toBe(true);
  });

  test('should prevent SSE connection storm', async () => {
    // Simulate rapid SSE connection attempts
    const sseStormConfig = {
      type: 'sse-connection-storm',
      connectionsPerSecond: 50,
      duration: 8000, // 8 seconds
      includeInvalidConnections: true
    };
    
    await stormSimulator.simulateSSEStorm(sseStormConfig);
    
    // Verify connection limiting worked
    const sseMetrics = await stormSimulator.getSSEStormMetrics();
    expect(sseMetrics.activeConnections).toBeLessThanOrEqual(1);
    expect(sseMetrics.rejectedConnections).toBeGreaterThan(0);
    expect(sseMetrics.connectionLeaks).toBe(0);
    
    // Verify escape sequences weren't generated by connection chaos
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.connectionStormDetected).toBe(false);
  });

  test('should handle keyboard input storm', async () => {
    await claudePage.clickSpawnButton();
    await claudePage.waitForProcessSpawn();
    
    // Simulate rapid keyboard input
    const inputStormConfig = {
      type: 'keyboard-storm',
      keysPerSecond: 200,
      duration: 5000,
      includeSpecialKeys: true,
      includeUnicode: true
    };
    
    await stormSimulator.simulateInputStorm(inputStormConfig);
    
    // Verify input throttling
    const inputMetrics = await stormSimulator.getInputStormMetrics();
    expect(inputMetrics.processedInputs).toBeLessThan(inputMetrics.attemptedInputs);
    expect(inputMetrics.droppedInputs).toBeGreaterThan(0);
    
    // Verify terminal state remains stable
    const terminalStable = await claudePage.checkTerminalStability();
    expect(terminalStable).toBe(true);
    
    // Verify no input-related escape sequences
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.inputEscapeSequences).toBeLessThan(10);
  });

  test('should survive process crash storm', async () => {
    // Start multiple processes and crash them rapidly
    const crashStormConfig = {
      type: 'process-crash-storm',
      processCount: 10,
      crashInterval: 500, // Crash every 500ms
      includeSegfault: true,
      includeHangups: true
    };
    
    await stormSimulator.simulateCrashStorm(crashStormConfig);
    
    // Verify crash recovery
    const crashMetrics = await stormSimulator.getCrashStormMetrics();
    expect(crashMetrics.processesStarted).toBe(10);
    expect(crashMetrics.processesCrashed).toBe(10);
    expect(crashMetrics.orphanedProcesses).toBe(0);
    
    // Verify UI remained functional
    const uiFunctional = await claudePage.checkUIFunctionality();
    expect(uiFunctional).toBe(true);
    
    // Verify escape sequences didn't flood from crashes
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.crashEscapeSequences).toBeLessThan(50);
  });

  test('should handle memory pressure storm', async () => {
    await claudePage.clickSpawnButton();
    await claudePage.waitForProcessSpawn();
    
    // Simulate memory pressure
    const memoryStormConfig = {
      type: 'memory-pressure',
      targetMemoryMB: 800, // Try to use 800MB
      allocationRate: 50, // MB per second
      includeFragmentation: true
    };
    
    await stormSimulator.simulateMemoryStorm(memoryStormConfig);
    
    // Verify memory management
    const memoryMetrics = await resourceMonitor.getMemoryMetrics();
    expect(memoryMetrics.peakUsage).toBeLessThan(1024 * 1024 * 1024); // < 1GB
    expect(memoryMetrics.leaks).toBe(0);
    expect(memoryMetrics.gcPressure).toBeGreaterThan(0); // GC was active
    
    // Verify terminal functionality under pressure
    const terminalWorking = await claudePage.testTerminalBasicFunctionality();
    expect(terminalWorking).toBe(true);
    
    // Verify escape sequences weren't corrupted by memory pressure
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.memoryCorruption).toBe(false);
  });

  test('should handle network interruption storm', async () => {
    await claudePage.clickSpawnButton();
    await claudePage.waitForProcessSpawn();
    
    // Simulate network interruptions
    const networkStormConfig = {
      type: 'network-interruption',
      interruptionsPerMinute: 20,
      duration: 60000, // 1 minute
      includeTimeouts: true,
      includeConnectionResets: true
    };
    
    await stormSimulator.simulateNetworkStorm(networkStormConfig);
    
    // Verify network resilience
    const networkMetrics = await stormSimulator.getNetworkStormMetrics();
    expect(networkMetrics.successfulReconnections).toBeGreaterThan(0);
    expect(networkMetrics.permanentFailures).toBe(0);
    
    // Verify terminal remained connected
    const terminalConnected = await claudePage.checkTerminalConnection();
    expect(terminalConnected).toBe(true);
    
    // Verify no network-related escape sequences
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.networkEscapeSequences).toBeLessThan(5);
  });

  test('should handle resize storm', async () => {
    await claudePage.clickSpawnButton();
    await claudePage.waitForProcessSpawn();
    
    // Simulate rapid window resizing
    const resizeStormConfig = {
      type: 'resize-storm',
      resizesPerSecond: 10,
      duration: 10000, // 10 seconds
      minWidth: 400,
      maxWidth: 1600,
      minHeight: 300,
      maxHeight: 1200
    };
    
    await stormSimulator.simulateResizeStorm(resizeStormConfig);
    
    // Verify resize handling
    const resizeMetrics = await stormSimulator.getResizeStormMetrics();
    expect(resizeMetrics.resizeEvents).toBeGreaterThan(50);
    expect(resizeMetrics.terminalReflows).toBeLessThan(resizeMetrics.resizeEvents); // Throttling worked
    
    // Verify terminal content integrity
    const terminalIntact = await claudePage.checkTerminalContentIntegrity();
    expect(terminalIntact).toBe(true);
    
    // Verify no resize-induced escape sequence storms
    const escapeReport = await escapeMonitor.getReport();
    expect(escapeReport.resizeStormDetected).toBe(false);
  });
});