/**
 * Comprehensive Test Suite for Claude Instance Endpoints
 * Generated by TDD London School Swarm Agent
 * Validates all 4 Claude instance button scenarios
 */

const request = require('supertest');
const express = require('express');

describe('Claude Instance Endpoint Validation Suite', () => {
  let app;
  let server;
  
  beforeAll(async () => {
    // Use the already running backend server on port 3000
    // No need to start a new server since simple-backend.js is already running
    app = { 
      // Mock app object for supertest to use the running server
      address: 'http://localhost:3000'
    };
    
    // Wait a moment to ensure server is ready
    await new Promise(resolve => setTimeout(resolve, 500));
  });
  
  afterAll(async () => {
    // No server cleanup needed since we're using the existing running server
  });
  
  describe('GET /api/claude/instances - Fetch Instances', () => {
    test('should return list of Claude instances', async () => {
      const response = await request('http://localhost:3000')
        .get('/api/claude/instances')
        .expect(200);
        
      expect(response.body).toMatchObject({
        success: true,
        instances: expect.any(Array),
        timestamp: expect.any(String)
      });
      
      expect(response.body.instances.length).toBeGreaterThan(0);
      
      // Validate instance structure
      response.body.instances.forEach(instance => {
        expect(instance).toMatchObject({
          id: expect.any(String),
          name: expect.any(String), 
          status: expect.stringMatching(/^(running|stopped|starting|error)$/),
          pid: expect.any(Number),
          startTime: expect.any(String)
        });
      });
    });
    
    test('should handle empty instance list gracefully', async () => {
      const response = await request('http://localhost:3000')
        .get('/api/claude/instances')
        .expect(200);
        
      expect(response.body.success).toBe(true);
      expect(Array.isArray(response.body.instances)).toBe(true);
    });
  });
  
  describe('POST /api/claude/instances - Create Instance Scenarios', () => {
    test('Button 1: prod/claude - should create production instance', async () => {
      const requestBody = {
        command: ['claude'],
        workingDirectory: '/workspaces/agent-feed/prod'
      };
      
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send(requestBody)
        .expect(201);
        
      expect(response.body).toMatchObject({
        success: true,
        instanceId: expect.any(String),
        instance: expect.objectContaining({
          name: 'prod/claude',
          status: 'starting',
          command: requestBody.command,
          workingDirectory: requestBody.workingDirectory
        }),
        message: 'Claude instance created successfully'
      });
    });
    
    test('Button 2: skip-permissions - should create skip-permissions instance', async () => {
      const requestBody = {
        command: ['claude', '--dangerously-skip-permissions'],
        workingDirectory: '/workspaces/agent-feed/prod'
      };
      
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send(requestBody)
        .expect(201);
        
      expect(response.body.instance.name).toBe('skip-permissions');
      expect(response.body.instance.command).toEqual(requestBody.command);
    });
    
    test('Button 3: skip-permissions -c - should create skip-permissions -c instance', async () => {
      const requestBody = {
        command: ['claude', '--dangerously-skip-permissions', '-c'],
        workingDirectory: '/workspaces/agent-feed/prod'
      };
      
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send(requestBody)
        .expect(201);
        
      expect(response.body.instance.name).toBe('skip-permissions -c');
      expect(response.body.instance.command).toEqual(requestBody.command);
    });
    
    test('Button 4: skip-permissions --resume - should create resume instance', async () => {
      const requestBody = {
        command: ['claude', '--dangerously-skip-permissions', '--resume'],
        workingDirectory: '/workspaces/agent-feed/prod'
      };
      
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send(requestBody)
        .expect(201);
        
      expect(response.body.instance.name).toBe('skip-permissions --resume');
      expect(response.body.instance.command).toEqual(requestBody.command);
    });
    
    test('should generate unique instance IDs and PIDs', async () => {
      const requests = Array(3).fill().map(() => 
        request(app)
          .post('/api/claude/instances')
          .send({
            command: ['claude'],
            workingDirectory: '/workspaces/agent-feed/prod'
          })
      );
      
      const responses = await Promise.all(requests);
      
      const instanceIds = responses.map(r => r.body.instanceId);
      const pids = responses.map(r => r.body.instance.pid);
      
      // All IDs should be unique
      expect(new Set(instanceIds).size).toBe(instanceIds.length);
      expect(new Set(pids).size).toBe(pids.length);
    });
  });
  
  describe('DELETE /api/claude/instances/:instanceId - Terminate Instance', () => {
    let testInstanceId;
    
    beforeEach(async () => {
      // Create a test instance
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send({
          command: ['claude'],
          workingDirectory: '/workspaces/agent-feed/prod'
        });
      
      testInstanceId = response.body.instanceId;
    });
    
    test('should terminate instance successfully', async () => {
      const response = await request('http://localhost:3000')
        .delete(`/api/claude/instances/${testInstanceId}`)
        .expect(200);
        
      expect(response.body).toMatchObject({
        success: true,
        instanceId: testInstanceId,
        message: expect.stringContaining('terminated successfully')
      });
    });
    
    test('should handle non-existent instance gracefully', async () => {
      const response = await request('http://localhost:3000')
        .delete('/api/claude/instances/non-existent-id')
        .expect(200);
        
      expect(response.body.success).toBe(true);
    });
  });
  
  describe('Error Handling and Edge Cases', () => {
    test('should handle malformed POST requests', async () => {
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send({}) // Empty body
        .expect(201); // Should still work with defaults
        
      expect(response.body.success).toBe(true);
      expect(response.body.instance.name).toBe('Claude Instance');
    });
    
    test('should handle invalid command arrays', async () => {
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send({
          command: 'invalid-string-command', // Should be array
          workingDirectory: '/workspaces/agent-feed/prod'
        })
        .expect(201);
        
      expect(response.body.success).toBe(true);
    });
  });
  
  describe('Performance and Load Testing', () => {
    test('should handle concurrent instance creation', async () => {
      const concurrentRequests = Array(5).fill().map(() =>
        request(app)
          .post('/api/claude/instances')
          .send({
            command: ['claude'],
            workingDirectory: '/workspaces/agent-feed/prod'
          })
      );
      
      const responses = await Promise.all(concurrentRequests);
      
      responses.forEach(response => {
        expect(response.status).toBe(201);
        expect(response.body.success).toBe(true);
      });
      
      // All should have unique instance IDs
      const instanceIds = responses.map(r => r.body.instanceId);
      expect(new Set(instanceIds).size).toBe(instanceIds.length);
    });
  });
  
  describe('Integration with Frontend ClaudeInstanceManager', () => {
    test('should match frontend API expectations for fetchInstances', async () => {
      const response = await request('http://localhost:3000')
        .get('/api/claude/instances')
        .expect(200);
        
      // Should match the structure expected by ClaudeInstanceManager.tsx line 115-117
      expect(response.body.success).toBe(true);
      expect(response.body.instances).toBeDefined();
      
      if (response.body.instances.length > 0) {
        const instance = response.body.instances[0];
        expect(instance).toMatchObject({
          id: expect.any(String),
          name: expect.any(String),
          status: expect.any(String),
          pid: expect.any(Number)
        });
      }
    });
    
    test('should match frontend API expectations for createInstance', async () => {
      const response = await request('http://localhost:3000')
        .post('/api/claude/instances')
        .send({
          command: ['claude'],
          workingDirectory: '/workspaces/agent-feed/prod'
        })
        .expect(201);
        
      // Should match the structure expected by ClaudeInstanceManager.tsx line 175-179
      expect(response.body.success).toBe(true);
      expect(response.body.instanceId).toBeDefined();
    });
  });
});