#!/bin/bash
# AUTOMATED FIXES FOR CRITICAL ISSUES
# Generated by regression test suite

echo "🔧 Starting automated fixes for Settings removal issues..."

# Fix import paths in CostOverviewDashboard.tsx
echo "📝 Fixing import paths..."
cd /workspaces/agent-feed

# Ensure button component exists and has correct exports
if [ -f "frontend/src/components/ui/button.tsx" ]; then
    echo "✅ Button component exists"
else
    echo "❌ Button component missing - needs manual creation"
fi

# Fix relative import paths
sed -i 's|@/components/ui/button|../ui/button|g' frontend/src/components/analytics/CostOverviewDashboard.tsx
sed -i 's|@/lib/utils|../../lib/utils|g' frontend/src/components/analytics/CostOverviewDashboard.tsx
sed -i 's|@/components/charts/|../charts/|g' frontend/src/components/analytics/CostOverviewDashboard.tsx

echo "✅ Import path fixes applied"

# Install missing dependencies if needed
echo "📦 Checking dependencies..."
npm install

# Try to rebuild node-pty for the current platform
echo "🔨 Rebuilding native dependencies..."
npm rebuild node-pty 2>/dev/null || echo "⚠️ node-pty rebuild failed - this is expected in some environments"

echo "🎯 Automated fixes complete. Manual verification needed for remaining issues."
