/**
 * TDD Test Patterns for White Screen of Death Prevention
 * Generated by NLD Agent based on WSOD-TS-20250823-001 failure pattern
 */

import { describe, test, expect, beforeAll } from '@jest/globals';
import { execSync } from 'child_process';
import { readFileSync, existsSync } from 'fs';
import { glob } from 'glob';

describe('WSOD Prevention Test Suite', () => {
  
  describe('TypeScript Build Validation', () => {
    test('should compile TypeScript without errors', () => {
      expect(() => {
        execSync('npx tsc --noEmit --project tsconfig.json', { 
          stdio: 'pipe',
          timeout: 30000
        });
      }).not.toThrow();
    });

    test('should build frontend successfully', () => {
      expect(() => {
        execSync('npm run build', { 
          stdio: 'pipe',
          timeout: 60000,
          cwd: './frontend'
        });
      }).not.toThrow();
    });

    test('should not have TypeScript compilation errors in console', () => {
      try {
        const output = execSync('npx tsc --noEmit 2>&1', { 
          encoding: 'utf8',
          cwd: './frontend'
        });
        
        // Check for common TS error codes that cause WSOD
        expect(output).not.toMatch(/TS2322:/); // Type assignment errors
        expect(output).not.toMatch(/TS2353:/); // Unknown properties
        expect(output).not.toMatch(/TS2305:/); // Module not found
        expect(output).not.toMatch(/TS2769:/); // Overload mismatch
        
      } catch (error: any) {
        throw new Error(`TypeScript compilation failed: ${error.stdout}`);
      }
    });
  });

  describe('Component Interface Validation', () => {
    test('should validate React component prop interfaces', async () => {
      const componentFiles = await glob('frontend/src/components/**/*.tsx');
      
      for (const file of componentFiles) {
        const content = readFileSync(file, 'utf8');
        
        // Check for common prop interface issues
        expect(content).not.toMatch(/jsx:\s*true/); // Invalid JSX prop on HTML elements
        expect(content).not.toMatch(/cacheTime:/); // Deprecated React Query prop
        expect(content).not.toMatch(/fractionalSecondDigits:/); // Invalid DateTimeFormat option
      }
    });

    test('should ensure ErrorBoundary components have correct props', async () => {
      const errorBoundaryFiles = await glob('frontend/src/components/**/*ErrorBoundary*.tsx');
      
      for (const file of errorBoundaryFiles) {
        const content = readFileSync(file, 'utf8');
        
        // Check ErrorBoundary prop compatibility
        expect(content).not.toMatch(/resetOnPropsChange:/); // Invalid prop for react-error-boundary
        expect(content).not.toMatch(/FallbackComponent.*ReactNode/); // Invalid type assignment
      }
    });

    test('should validate Terminal component prop interfaces', async () => {
      const terminalFiles = await glob('frontend/src/components/**/*Terminal*.tsx');
      
      for (const file of terminalFiles) {
        const content = readFileSync(file, 'utf8');
        
        // Check Terminal-specific prop issues
        expect(content).not.toMatch(/autoConnect.*TerminalProps/); // Invalid Terminal prop
        expect(content).not.toMatch(/ref.*TerminalProps/); // Ref forwarding issues
      }
    });
  });

  describe('Import Resolution Validation', () => {
    test('should resolve all component imports', async () => {
      const sourceFiles = await glob('frontend/src/**/*.{ts,tsx}');
      
      for (const file of sourceFiles) {
        const content = readFileSync(file, 'utf8');
        const importMatches = content.match(/import.*from\s+['"]([^'"]+)['"]/g);
        
        if (importMatches) {
          for (const importStatement of importMatches) {
            const pathMatch = importStatement.match(/from\s+['"]([^'"]+)['"]/);
            if (pathMatch && pathMatch[1].startsWith('.')) {
              const importPath = pathMatch[1];
              // Validate relative imports exist
              expect(importPath).toBeDefined();
              // Add more specific validation based on the import path
            }
          }
        }
      }
    });

    test('should not have missing component exports', async () => {
      const componentFiles = await glob('frontend/src/components/**/*.tsx');
      
      for (const file of componentFiles) {
        const content = readFileSync(file, 'utf8');
        
        // Check for common export issues that cause import failures
        if (content.includes('TerminalDebugComponent')) {
          expect(content).toMatch(/export.*TerminalDebugComponent/);
        }
      }
    });
  });

  describe('JSX Syntax Validation', () => {
    test('should not have invalid JSX syntax', async () => {
      const jsxFiles = await glob('frontend/src/**/*.tsx');
      
      for (const file of jsxFiles) {
        const content = readFileSync(file, 'utf8');
        
        // Check for invalid JSX syntax patterns
        expect(content).not.toMatch(/<style[^>]*jsx\s*=\s*{?true}?[^>]*>/); // Invalid jsx prop on style
        expect(content).not.toMatch(/title\s*=.*LucideProps/); // Invalid Lucide icon props
      }
    });

    test('should validate React Query configuration', async () => {
      const queryFiles = await glob('frontend/src/**/*.{ts,tsx}');
      
      for (const file of queryFiles) {
        const content = readFileSync(file, 'utf8');
        
        if (content.includes('useQuery') || content.includes('QueryClient')) {
          // Check for deprecated React Query options
          expect(content).not.toMatch(/cacheTime:/); // Use staleTime instead
          expect(content).not.toMatch(/refetchOnWindowFocus:\s*true/); // Explicit boolean not needed
        }
      }
    });
  });

  describe('Browser Smoke Tests', () => {
    test('should render app without white screen', async () => {
      // This would typically use a headless browser like Puppeteer
      // For now, we'll check that the main App component can be imported
      expect(async () => {
        const { default: App } = await import('../frontend/src/App');
        expect(App).toBeDefined();
      }).not.toThrow();
    });

    test('should mount key components without errors', async () => {
      // Test that critical components can be imported and don't have obvious issues
      const criticalComponents = [
        'SimpleLauncher',
        'EnhancedTerminal', 
        'AgentManager',
        'ErrorBoundary'
      ];

      for (const componentName of criticalComponents) {
        try {
          const componentPath = `../frontend/src/components/${componentName}`;
          const component = await import(componentPath);
          expect(component).toBeDefined();
        } catch (error: any) {
          // If import fails, that's a critical issue
          throw new Error(`Critical component ${componentName} failed to import: ${error.message}`);
        }
      }
    });
  });

  describe('Performance and Bundle Validation', () => {
    test('should generate valid build artifacts', () => {
      // Run build and check that output files are created
      execSync('npm run build', { cwd: './frontend', stdio: 'pipe' });
      
      expect(existsSync('./frontend/dist/index.html')).toBe(true);
      expect(existsSync('./frontend/dist/assets')).toBe(true);
    });

    test('should not have bundle size regressions', () => {
      // This would compare bundle sizes against baseline
      // For now, just ensure build completes and creates output
      const distPath = './frontend/dist';
      expect(existsSync(distPath)).toBe(true);
    });
  });
});

/**
 * Custom Jest Matchers for WSOD Prevention
 */
expect.extend({
  toNotCauseWhiteScreen(received: string) {
    const hasTypeScriptErrors = received.includes('TS2322:') || 
                               received.includes('TS2353:') || 
                               received.includes('TS2305:');
    
    const hasJSXErrors = received.includes('jsx:') && received.includes('HTMLStyleElement');
    
    const hasImportErrors = received.includes('has no exported member');

    if (hasTypeScriptErrors || hasJSXErrors || hasImportErrors) {
      return {
        message: () => `Expected code not to cause white screen, but found critical errors that lead to WSOD`,
        pass: false
      };
    }

    return {
      message: () => `Code appears safe from white screen issues`,
      pass: true
    };
  }
});

declare global {
  namespace jest {
    interface Matchers<R> {
      toNotCauseWhiteScreen(): R;
    }
  }
}