/**
 * Professional Button Component
 * Claudable-styled button with comprehensive functionality
 * Generated by UI Component Development Agent
 */

import React, { forwardRef, ButtonHTMLAttributes } from 'react';
import { cn } from '../utils/cn';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive';
  size?: 'sm' | 'md' | 'lg' | 'icon';
  isLoading?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  fullWidth?: boolean;
}

const buttonVariants = {
  primary: 'bg-blue-500 text-white hover:bg-blue-600 focus:ring-blue-500 shadow-sm',
  secondary: 'bg-gray-100 text-gray-900 hover:bg-gray-200 focus:ring-gray-500 dark:bg-gray-700 dark:text-gray-100 dark:hover:bg-gray-600',
  outline: 'border border-gray-200 bg-white text-gray-900 hover:bg-gray-50 focus:ring-gray-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100 dark:hover:bg-gray-700',
  ghost: 'text-gray-700 hover:bg-gray-100 focus:ring-gray-500 dark:text-gray-300 dark:hover:bg-gray-700',
  destructive: 'bg-red-500 text-white hover:bg-red-600 focus:ring-red-500 shadow-sm'
};

const buttonSizes = {
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
  icon: 'p-2'
};

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({
  className,
  variant = 'primary',
  size = 'md',
  isLoading = false,
  leftIcon,
  rightIcon,
  fullWidth = false,
  children,
  disabled,
  ...props
}, ref) => {
  const isDisabled = disabled || isLoading;

  return (
    <button
      ref={ref}
      className={cn(
        // Base styles
        'inline-flex items-center justify-center gap-2 font-medium rounded-lg transition-all duration-200',
        'focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white dark:focus:ring-offset-gray-900',
        'disabled:opacity-50 disabled:cursor-not-allowed',
        
        // Variant styles
        buttonVariants[variant],
        
        // Size styles
        buttonSizes[size],
        
        // Full width
        fullWidth && 'w-full',
        
        // Loading state
        isLoading && 'cursor-wait',
        
        className
      )}
      disabled={isDisabled}
      {...props}
    >
      {/* Left icon or loading spinner */}
      {isLoading ? (
        <svg 
          className="w-4 h-4 animate-spin" 
          fill="none" 
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <circle 
            className="opacity-25" 
            cx="12" 
            cy="12" 
            r="10" 
            stroke="currentColor" 
            strokeWidth="4"
          />
          <path 
            className="opacity-75" 
            fill="currentColor" 
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
          />
        </svg>
      ) : leftIcon ? (
        <span className="flex-shrink-0" aria-hidden="true">
          {leftIcon}
        </span>
      ) : null}
      
      {/* Button content */}
      {children && (
        <span className={cn(
          'truncate',
          size === 'icon' && 'sr-only'
        )}>
          {children}
        </span>
      )}
      
      {/* Right icon */}
      {rightIcon && !isLoading && (
        <span className="flex-shrink-0" aria-hidden="true">
          {rightIcon}
        </span>
      )}
    </button>
  );
});

Button.displayName = 'Button';

// Specialized button variants for common use cases
export const SendButton = forwardRef<HTMLButtonElement, Omit<ButtonProps, 'variant' | 'size' | 'rightIcon'>>(
  ({ className, children = 'Send', ...props }, ref) => (
    <Button
      ref={ref}
      variant="primary"
      size="md"
      className={cn('rounded-full', className)}
      rightIcon={
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
          <path 
            d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z" 
            stroke="currentColor" 
            strokeWidth="2" 
            strokeLinecap="round" 
            strokeLinejoin="round"
          />
        </svg>
      }
      {...props}
    >
      {children}
    </Button>
  )
);

SendButton.displayName = 'SendButton';

export const IconButton = forwardRef<HTMLButtonElement, Omit<ButtonProps, 'size'>>(
  ({ className, children, ...props }, ref) => (
    <Button
      ref={ref}
      size="icon"
      variant="ghost"
      className={cn('rounded-full', className)}
      {...props}
    >
      {children}
    </Button>
  )
);

IconButton.displayName = 'IconButton';

export const FileUploadButton = forwardRef<HTMLButtonElement, Omit<ButtonProps, 'variant' | 'leftIcon'>>(
  ({ className, children = 'Upload', ...props }, ref) => (
    <Button
      ref={ref}
      variant="outline"
      className={className}
      leftIcon={
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
          <path 
            d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" 
            stroke="currentColor" 
            strokeWidth="2" 
            strokeLinecap="round" 
            strokeLinejoin="round"
          />
        </svg>
      }
      {...props}
    >
      {children}
    </Button>
  )
);

FileUploadButton.displayName = 'FileUploadButton';

export { Button };