/**
 * Modern ChatInterface Component
 * Professional chat interface with Claudable styling and intelligent features
 * Generated by ChatInterface Development Agent
 */

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../utils/cn';
import { MessageList, Message } from './MessageList';
import { MessageInput, ImageAttachment } from './MessageInput';
import { Button, IconButton } from './Button';

export interface ChatInterfaceProps {
  projectId?: string;
  conversationId?: string;
  mode?: 'chat' | 'code' | 'assistant';
  title?: string;
  className?: string;
  
  // Message handling
  messages: Message[];
  isLoading?: boolean;
  isConnected?: boolean;
  
  // Callbacks
  onSendMessage?: (content: string, images?: ImageAttachment[]) => Promise<void>;
  onClearMessages?: () => void;
  onModeChange?: (mode: 'chat' | 'code' | 'assistant') => void;
  onSettingsClick?: () => void;
  
  // Configuration
  enableImageUpload?: boolean;
  enableModeSwitch?: boolean;
  enableClearButton?: boolean;
  maxMessageLength?: number;
}

const modeConfig = {
  chat: {
    label: 'Chat',
    icon: (
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
      </svg>
    ),
    placeholder: 'Type a message...',
    description: 'General conversation'
  },
  code: {
    label: 'Code',
    icon: (
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
              d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
      </svg>
    ),
    placeholder: 'Describe what you want to build...',
    description: 'Code generation and development'
  },
  assistant: {
    label: 'Assistant',
    icon: (
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
              d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
    ),
    placeholder: 'Ask your AI assistant...',
    description: 'Intelligent assistance'
  }
};

const ConnectionStatus: React.FC<{ isConnected?: boolean; isLoading?: boolean }> = ({ 
  isConnected, 
  isLoading 
}) => (
  <div className="flex items-center gap-2">
    <div className={cn(
      'w-2 h-2 rounded-full transition-all duration-300',
      isLoading 
        ? 'bg-yellow-400 animate-pulse' 
        : isConnected 
        ? 'bg-green-400' 
        : 'bg-red-400'
    )} />
    <span className="text-xs text-gray-500 dark:text-gray-400">
      {isLoading ? 'Processing...' : isConnected ? 'Connected' : 'Disconnected'}
    </span>
  </div>
);

const ModeSelector: React.FC<{
  currentMode: 'chat' | 'code' | 'assistant';
  onModeChange: (mode: 'chat' | 'code' | 'assistant') => void;
  disabled?: boolean;
}> = ({ currentMode, onModeChange, disabled }) => {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const currentConfig = modeConfig[currentMode];

  return (
    <div ref={dropdownRef} className="relative">
      <Button
        variant="outline"
        size="sm"
        onClick={() => setIsOpen(!isOpen)}
        disabled={disabled}
        className="gap-2"
      >
        {currentConfig.icon}
        <span>{currentConfig.label}</span>
        <svg className={cn(
          'w-3 h-3 transition-transform duration-200',
          isOpen && 'rotate-180'
        )} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </Button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: -10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -10, scale: 0.95 }}
            transition={{ duration: 0.15 }}
            className="absolute top-full left-0 mt-2 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded-lg shadow-lg py-2 min-w-[200px] z-50"
          >
            {Object.entries(modeConfig).map(([mode, config]) => (
              <button
                key={mode}
                onClick={() => {
                  onModeChange(mode as 'chat' | 'code' | 'assistant');
                  setIsOpen(false);
                }}
                className={cn(
                  'w-full px-4 py-2 text-left flex items-center gap-3 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors',
                  currentMode === mode && 'bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400'
                )}
              >
                {config.icon}
                <div>
                  <div className="font-medium text-sm">{config.label}</div>
                  <div className="text-xs text-gray-500 dark:text-gray-400">{config.description}</div>
                </div>
                {currentMode === mode && (
                  <svg className="w-4 h-4 ml-auto text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                )}
              </button>
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export const ChatInterface: React.FC<ChatInterfaceProps> = ({
  projectId,
  conversationId,
  mode = 'chat',
  title,
  className,
  messages,
  isLoading = false,
  isConnected = true,
  onSendMessage,
  onClearMessages,
  onModeChange,
  onSettingsClick,
  enableImageUpload = true,
  enableModeSwitch = true,
  enableClearButton = true,
  maxMessageLength = 2000
}) => {
  const [currentMode, setCurrentMode] = useState<'chat' | 'code' | 'assistant'>(mode);
  const [isTyping, setIsTyping] = useState(false);

  const handleModeChange = useCallback((newMode: 'chat' | 'code' | 'assistant') => {
    setCurrentMode(newMode);
    onModeChange?.(newMode);
  }, [onModeChange]);

  const handleSendMessage = useCallback(async (content: string, images?: ImageAttachment[]) => {
    if (onSendMessage) {
      await onSendMessage(content, images);
    }
  }, [onSendMessage]);

  const handleClear = useCallback(() => {
    if (onClearMessages && messages.length > 0) {
      if (window.confirm('Are you sure you want to clear all messages?')) {
        onClearMessages();
      }
    }
  }, [onClearMessages, messages.length]);

  const currentConfig = modeConfig[currentMode];
  const hasMessages = messages.length > 0;

  return (
    <div className={cn(
      'flex flex-col h-full bg-white dark:bg-gray-900 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700',
      'overflow-hidden',
      className
    )}>
      {/* Header */}
      <div className="flex-shrink-0 bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            {/* Title */}
            <div className="flex items-center gap-2">
              {currentConfig.icon}
              <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                {title || `${currentConfig.label} Interface`}
              </h2>
            </div>

            {/* Connection status */}
            <ConnectionStatus isConnected={isConnected} isLoading={isLoading} />
          </div>

          <div className="flex items-center gap-2">
            {/* Mode selector */}
            {enableModeSwitch && (
              <ModeSelector
                currentMode={currentMode}
                onModeChange={handleModeChange}
                disabled={isLoading}
              />
            )}

            {/* Clear button */}
            {enableClearButton && hasMessages && (
              <IconButton
                onClick={handleClear}
                disabled={isLoading}
                title="Clear messages"
                variant="outline"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              </IconButton>
            )}

            {/* Settings button */}
            {onSettingsClick && (
              <IconButton
                onClick={onSettingsClick}
                title="Settings"
                variant="outline"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
                        d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </IconButton>
            )}
          </div>
        </div>

        {/* Mode description */}
        <div className="mt-2 text-sm text-gray-600 dark:text-gray-400">
          {currentConfig.description}
          {isTyping && (
            <span className="ml-2 inline-flex items-center gap-1">
              <span>•</span>
              <span className="text-blue-500">Typing...</span>
            </span>
          )}
        </div>
      </div>

      {/* Messages */}
      <MessageList 
        messages={messages}
        isLoading={isLoading}
        className="flex-1"
      />

      {/* Input */}
      <MessageInput
        placeholder={currentConfig.placeholder}
        disabled={!isConnected}
        isLoading={isLoading}
        allowImages={enableImageUpload}
        maxLength={maxMessageLength}
        onSend={handleSendMessage}
        onTyping={setIsTyping}
        className="flex-shrink-0"
      />

      {/* Footer info */}
      {projectId && (
        <div className="flex-shrink-0 px-4 py-2 bg-gray-50 dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
            <span>Project: {projectId}</span>
            {conversationId && <span>Conversation: {conversationId}</span>}
          </div>
        </div>
      )}
    </div>
  );
};

export default ChatInterface;