/**
 * Modern MessageInput Component
 * Professional message input with file upload and Claudable styling
 * Generated by MessageInput Development Agent
 */

import React, { useState, useRef, useCallback, KeyboardEvent, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../utils/cn';
import { Button, IconButton, FileUploadButton } from './Button';

export interface ImageAttachment {
  id: string;
  file: File;
  url: string;
  name: string;
  size: number;
  type: string;
}

export interface MessageInputProps {
  placeholder?: string;
  disabled?: boolean;
  isLoading?: boolean;
  maxLength?: number;
  allowImages?: boolean;
  maxImages?: number;
  className?: string;
  onSend: (content: string, images?: ImageAttachment[]) => void | Promise<void>;
  onTyping?: (isTyping: boolean) => void;
}

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
const SUPPORTED_IMAGE_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];

export const MessageInput: React.FC<MessageInputProps> = ({
  placeholder = 'Type a message...',
  disabled = false,
  isLoading = false,
  maxLength = 2000,
  allowImages = true,
  maxImages = 5,
  className,
  onSend,
  onTyping
}) => {
  const [content, setContent] = useState('');
  const [images, setImages] = useState<ImageAttachment[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const typingTimeoutRef = useRef<NodeJS.Timeout>();

  const isDisabled = disabled || isLoading;
  const canSend = (content.trim() || images.length > 0) && !isDisabled;
  const characterCount = content.length;
  const isNearLimit = characterCount > maxLength * 0.8;
  const isOverLimit = characterCount > maxLength;

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      textarea.style.height = Math.min(textarea.scrollHeight, 120) + 'px';
    }
  }, [content]);

  // Handle typing indicator
  useEffect(() => {
    if (onTyping) {
      onTyping(content.length > 0);
      
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }
      
      typingTimeoutRef.current = setTimeout(() => {
        onTyping(false);
      }, 1000);
    }

    return () => {
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }
    };
  }, [content, onTyping]);

  const handleSend = useCallback(async () => {
    if (!canSend || isOverLimit) return;

    const trimmedContent = content.trim();
    if (!trimmedContent && images.length === 0) return;

    try {
      await onSend(trimmedContent, images.length > 0 ? images : undefined);
      setContent('');
      setImages([]);
      setUploadError(null);
      
      // Reset textarea height
      if (textareaRef.current) {
        textareaRef.current.style.height = 'auto';
      }
    } catch (error) {
      console.error('Failed to send message:', error);
    }
  }, [canSend, content, images, onSend, isOverLimit]);

  const handleKeyPress = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter') {
      if (e.shiftKey || e.ctrlKey || e.metaKey) {
        // Allow new line
        return;
      }
      
      e.preventDefault();
      handleSend();
    }
  };

  const handleImageUpload = useCallback(async (files: FileList | File[]) => {
    setUploadError(null);
    
    const fileArray = Array.from(files);
    const validFiles: File[] = [];
    
    // Validate files
    for (const file of fileArray) {
      if (!SUPPORTED_IMAGE_TYPES.includes(file.type)) {
        setUploadError(`${file.name} is not a supported image format`);
        continue;
      }
      
      if (file.size > MAX_FILE_SIZE) {
        setUploadError(`${file.name} is too large (max 10MB)`);
        continue;
      }
      
      validFiles.push(file);
    }
    
    // Check total image limit
    if (images.length + validFiles.length > maxImages) {
      setUploadError(`Maximum ${maxImages} images allowed`);
      return;
    }

    // Create image attachments
    const newImages: ImageAttachment[] = [];
    
    for (const file of validFiles) {
      const url = URL.createObjectURL(file);
      newImages.push({
        id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        file,
        url,
        name: file.name,
        size: file.size,
        type: file.type
      });
    }

    setImages(prev => [...prev, ...newImages]);
  }, [images.length, maxImages]);

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      handleImageUpload(files);
    }
    
    // Reset input
    e.target.value = '';
  };

  const removeImage = (imageId: string) => {
    setImages(prev => {
      const updated = prev.filter(img => img.id !== imageId);
      // Clean up object URL
      const removed = prev.find(img => img.id === imageId);
      if (removed) {
        URL.revokeObjectURL(removed.url);
      }
      return updated;
    });
  };

  // Drag and drop handlers
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    if (!isDragging && allowImages) {
      setIsDragging(true);
    }
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    // Only set to false if leaving the component entirely
    if (!e.currentTarget.contains(e.relatedTarget as Node)) {
      setIsDragging(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    
    if (!allowImages || isDisabled) return;
    
    const files = e.dataTransfer.files;
    if (files.length > 0) {
      handleImageUpload(files);
    }
  };

  // Format file size
  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  return (
    <div 
      className={cn(
        'bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700',
        'transition-all duration-200',
        isDragging && 'bg-blue-50 dark:bg-blue-900/20 border-blue-300 dark:border-blue-600',
        className
      )}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      {/* Drag overlay */}
      <AnimatePresence>
        {isDragging && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-blue-500/10 border-2 border-dashed border-blue-400 dark:border-blue-500 rounded-lg flex items-center justify-center z-10"
          >
            <div className="text-center">
              <svg className="w-12 h-12 mx-auto text-blue-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
                      d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              <p className="text-blue-600 dark:text-blue-400 font-medium">Drop images here</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="p-4">
        {/* Error message */}
        <AnimatePresence>
          {uploadError && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="mb-3 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
            >
              <div className="flex items-center gap-2 text-red-600 dark:text-red-400">
                <svg className="w-4 h-4 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} 
                        d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span className="text-sm">{uploadError}</span>
                <button
                  onClick={() => setUploadError(null)}
                  className="ml-auto text-red-400 hover:text-red-600 dark:hover:text-red-300"
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Image attachments */}
        <AnimatePresence>
          {images.length > 0 && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="mb-3"
            >
              <div className="flex flex-wrap gap-3">
                {images.map((image) => (
                  <motion.div
                    key={image.id}
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.8 }}
                    className="relative group"
                  >
                    <div className="relative">
                      <img
                        src={image.url}
                        alt={image.name}
                        className="w-20 h-20 object-cover rounded-lg border border-gray-200 dark:border-gray-600 shadow-sm"
                      />
                      <button
                        onClick={() => removeImage(image.id)}
                        className="absolute -top-2 -right-2 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity shadow-sm hover:bg-red-600"
                      >
                        ×
                      </button>
                    </div>
                    <div className="mt-1 text-xs text-gray-500 dark:text-gray-400 text-center truncate max-w-[80px]">
                      {formatFileSize(image.size)}
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Input area */}
        <div className="flex items-end gap-3">
          {/* File upload button */}
          {allowImages && (
            <>
              <IconButton
                type="button"
                onClick={() => fileInputRef.current?.click()}
                disabled={isDisabled || images.length >= maxImages}
                className="mb-1"
                title="Upload images"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} 
                        d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </IconButton>
              <input
                ref={fileInputRef}
                type="file"
                accept={SUPPORTED_IMAGE_TYPES.join(',')}
                multiple
                onChange={handleFileInputChange}
                className="hidden"
              />
            </>
          )}

          {/* Text input */}
          <div className="flex-1 relative">
            <textarea
              ref={textareaRef}
              value={content}
              onChange={(e) => setContent(e.target.value)}
              onKeyDown={handleKeyPress}
              placeholder={placeholder}
              disabled={isDisabled}
              rows={1}
              className={cn(
                'w-full resize-none bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-2xl px-4 py-3 pr-12',
                'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
                'text-gray-900 dark:text-gray-100 placeholder-gray-500 dark:placeholder-gray-400',
                'transition-colors duration-200',
                'disabled:opacity-50 disabled:cursor-not-allowed',
                'scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-600',
                isOverLimit && 'border-red-300 dark:border-red-600 focus:ring-red-500'
              )}
              style={{ minHeight: '48px', maxHeight: '120px' }}
            />
            
            {/* Character count */}
            {(isNearLimit || isOverLimit) && (
              <div className={cn(
                'absolute right-3 top-2 text-xs font-medium',
                isOverLimit 
                  ? 'text-red-500 dark:text-red-400' 
                  : 'text-amber-500 dark:text-amber-400'
              )}>
                {characterCount}/{maxLength}
              </div>
            )}
          </div>

          {/* Send button */}
          <Button
            onClick={handleSend}
            disabled={!canSend || isOverLimit}
            isLoading={isLoading}
            className="rounded-full p-3 mb-1"
            size="icon"
            title="Send message (Enter)"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} 
                    d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z" />
            </svg>
          </Button>
        </div>

        {/* Helper text */}
        {!isDisabled && (
          <div className="mt-2 flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
            <span>
              Press Enter to send, Shift+Enter for new line
            </span>
            {allowImages && (
              <span>
                {images.length}/{maxImages} images
              </span>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default MessageInput;