/**
 * Global Setup for Escape Sequence Storm TDD Tests
 * 
 * Prepares the test environment and validates that we can properly
 * reproduce the escape sequence storm conditions.
 */

module.exports = async () => {
  console.log('\n🔧 Setting up Escape Sequence Storm TDD Test Environment...\n');
  
  // Validate test environment
  console.log('✅ Node.js version:', process.version);
  console.log('✅ Test environment: jsdom');
  console.log('✅ Jest configuration: loaded');
  
  // Create test artifacts directory
  const fs = require('fs');
  const path = require('path');
  
  const testDir = path.join(__dirname);
  const artifactsDir = path.join(testDir, 'artifacts');
  const reportsDir = path.join(testDir, 'reports');
  const coverageDir = path.join(testDir, 'coverage');
  
  // Create directories if they don't exist
  [artifactsDir, reportsDir, coverageDir].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
  
  console.log('✅ Test directories created');
  
  // Set up test data
  const testMetadata = {
    testSuiteId: `storm-tdd-${Date.now()}`,
    startTime: new Date().toISOString(),
    environment: 'test',
    purpose: 'Demonstrate escape sequence storm root causes',
    expectedBehavior: 'Tests should FAIL initially',
    categories: [
      'Button Click Debouncing',
      'PTY Process Management',
      'SSE Connection Management',
      'Output Buffer Management',
      'End-to-End Integration'
    ],
    rootCauses: [
      'Multiple rapid instance spawning',
      'PTY process conflicts',
      'SSE connection multiplication',
      'Unbounded output buffering',
      'System-wide integration failures'
    ]
  };
  
  fs.writeFileSync(
    path.join(artifactsDir, 'test-metadata.json'),
    JSON.stringify(testMetadata, null, 2)
  );
  
  console.log('✅ Test metadata created');
  
  // Validate test dependencies
  try {
    require('@testing-library/react');
    require('@testing-library/jest-dom');
    console.log('✅ React Testing Library available');
  } catch (error) {
    console.warn('⚠️  React Testing Library not available:', error.message);
  }
  
  // Set global test configuration
  global.__ESCAPE_SEQUENCE_STORM_TDD__ = {
    testSuiteId: testMetadata.testSuiteId,
    startTime: testMetadata.startTime,
    artifactsDir,
    reportsDir,
    coverageDir
  };
  
  console.log('✅ Global test configuration set');
  
  // Create test summary template
  const summaryTemplate = `# Escape Sequence Storm TDD Test Summary

**Test Suite ID**: ${testMetadata.testSuiteId}
**Start Time**: ${testMetadata.startTime}

## Purpose
These tests demonstrate the root causes of terminal escape sequence storms by reproducing the exact failure conditions.

## Expected Results
- ⚠️ Tests SHOULD FAIL initially
- 🔍 Failures show broken behavior that causes storms  
- 🔧 After implementing fixes, tests should pass

## Test Categories
${testMetadata.categories.map(cat => `- ${cat}`).join('\n')}

## Root Causes Being Tested
${testMetadata.rootCauses.map(cause => `- ${cause}`).join('\n')}

---
*Template generated by global setup*
`;

  fs.writeFileSync(
    path.join(reportsDir, 'SUMMARY_TEMPLATE.md'),
    summaryTemplate
  );
  
  console.log('✅ Summary template created');
  console.log('');
  console.log('🚨 IMPORTANT REMINDERS:');
  console.log('   - These tests SHOULD FAIL initially');
  console.log('   - They demonstrate broken behavior causing escape sequence storms');
  console.log('   - Use failures to understand what needs to be fixed');
  console.log('   - After implementing fixes, re-run to verify solutions');
  console.log('');
  console.log('🎯 Test environment setup complete!\n');
};