/**
 * Mock API Service for Development
 * Provides mock data for all API endpoints when backend is unavailable
 */

// Mock data generators
const generateMockAgent = (id: string, name: string) => ({
  id,
  name,
  display_name: name,
  description: `AI agent specialized in ${name.toLowerCase()} tasks`,
  system_prompt: `You are ${name}, an advanced AI assistant specialized in ${name.toLowerCase()} operations.`,
  avatar_color: `#${Math.floor(Math.random()*16777215).toString(16)}`,
  capabilities: [
    'text-processing',
    'data-analysis', 
    'task-automation',
    'real-time-responses'
  ],
  status: Math.random() > 0.2 ? 'active' : 'inactive',
  created_at: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date(Date.now() - Math.random() * 24 * 60 * 60 * 1000).toISOString(),
  last_used: new Date(Date.now() - Math.random() * 12 * 60 * 60 * 1000).toISOString(),
  usage_count: Math.floor(Math.random() * 1000) + 50,
  performance_metrics: {
    success_rate: 85 + Math.random() * 15,
    average_response_time: 200 + Math.random() * 800,
    total_tokens_used: Math.floor(Math.random() * 100000) + 10000,
    error_count: Math.floor(Math.random() * 20)
  },
  health_status: {
    cpu_usage: Math.random() * 80 + 10,
    memory_usage: Math.random() * 70 + 20,
    response_time: 100 + Math.random() * 300,
    last_heartbeat: new Date().toISOString()
  }
});

const generateMockPost = (id: string) => ({
  id,
  title: `Agent Update ${id.slice(-4)}`,
  content: `This is a sample post generated by AI agent. Content includes important updates about system performance, new capabilities, and task completions. Random value: ${Math.random()}`,
  authorAgent: `Agent-${Math.floor(Math.random() * 10) + 1}`,
  publishedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
  metadata: {
    businessImpact: Math.floor(Math.random() * 100),
    tags: ['automation', 'AI', 'productivity', 'analysis'].slice(0, Math.floor(Math.random() * 4) + 1),
    isAgentResponse: Math.random() > 0.3
  },
  likes: Math.floor(Math.random() * 50) + 1,
  comments: Math.floor(Math.random() * 20),
  shares: Math.floor(Math.random() * 10)
});

const generateMockActivity = (id: string) => ({
  id,
  type: ['task_completed', 'agent_spawned', 'error_resolved', 'performance_update'][Math.floor(Math.random() * 4)],
  description: `Activity ${id}: System performed automated task with ${Math.floor(Math.random() * 100)}% success rate`,
  timestamp: new Date(Date.now() - Math.random() * 24 * 60 * 60 * 1000).toISOString(),
  agent_id: `agent-${Math.floor(Math.random() * 10) + 1}`,
  status: Math.random() > 0.1 ? 'completed' : 'failed',
  metadata: {
    duration: Math.floor(Math.random() * 5000) + 100,
    tokens_used: Math.floor(Math.random() * 1000) + 50
  }
});

// Mock API responses
export const mockApiService = {
  // Agent Posts API
  async getAgentPosts(): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 300 + Math.random() * 700)); // Simulate network delay
    
    const posts = Array.from({ length: 15 }, (_, i) => 
      generateMockPost(`post-${Date.now()}-${i}`)
    );
    
    return {
      success: true,
      data: posts,
      total: posts.length,
      page: 1,
      limit: 20
    };
  },

  // Agents API
  async getAgents(): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 200 + Math.random() * 500));
    
    const agentNames = [
      'DataAnalyzer', 'ContentCreator', 'TaskManager', 'CodeReviewer', 
      'ResearchAssistant', 'QualityController', 'PerformanceMonitor', 'SecurityGuard'
    ];
    
    const agents = agentNames.map((name, i) => 
      generateMockAgent(`agent-${i + 1}`, name)
    );
    
    return {
      success: true,
      agents,
      total: agents.length,
      active: agents.filter(a => a.status === 'active').length
    };
  },

  // Activities API
  async getActivities(): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 250 + Math.random() * 400));
    
    const activities = Array.from({ length: 20 }, (_, i) => 
      generateMockActivity(`activity-${Date.now()}-${i}`)
    );
    
    return {
      success: true,
      activities,
      total: activities.length
    };
  },

  // Analytics APIs
  async getPerformanceAnalytics(timeRange: string = '24h'): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 300 + Math.random() * 600));
    
    const hours = timeRange === '24h' ? 24 : timeRange === '7d' ? 168 : 720;
    const dataPoints = Math.min(hours, 48); // Limit data points for performance
    
    const metrics = Array.from({ length: dataPoints }, (_, i) => ({
      timestamp: new Date(Date.now() - (dataPoints - i) * 60 * 60 * 1000).toISOString(),
      cpu_usage: 20 + Math.random() * 60,
      memory_usage: 30 + Math.random() * 50,
      response_time: 100 + Math.random() * 400,
      throughput: Math.floor(Math.random() * 1000) + 100,
      error_rate: Math.random() * 5
    }));
    
    return {
      success: true,
      metrics,
      summary: {
        avg_cpu: metrics.reduce((a, b) => a + b.cpu_usage, 0) / metrics.length,
        avg_memory: metrics.reduce((a, b) => a + b.memory_usage, 0) / metrics.length,
        avg_response_time: metrics.reduce((a, b) => a + b.response_time, 0) / metrics.length,
        total_requests: Math.floor(Math.random() * 50000) + 10000,
        success_rate: 95 + Math.random() * 5
      }
    };
  },

  async getAgentAnalytics(timeRange: string = '24h'): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 250 + Math.random() * 500));
    
    return {
      success: true,
      agent_stats: [
        { name: 'DataAnalyzer', tasks_completed: 145, success_rate: 98.2, avg_response_time: 245 },
        { name: 'ContentCreator', tasks_completed: 89, success_rate: 96.7, avg_response_time: 312 },
        { name: 'TaskManager', tasks_completed: 203, success_rate: 99.1, avg_response_time: 178 },
        { name: 'CodeReviewer', tasks_completed: 67, success_rate: 94.8, avg_response_time: 523 }
      ],
      timeRange
    };
  },

  async getHealthAnalytics(): Promise<any> {
    await new Promise(resolve => setTimeout(resolve, 150 + Math.random() * 300));
    
    return {
      success: true,
      health: {
        overall_status: 'healthy',
        uptime: '99.97%',
        last_incident: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        active_agents: 8,
        total_agents: 12,
        system_load: 0.65,
        disk_usage: 0.42,
        network_latency: 23.5
      }
    };
  }
};

// Intercept fetch calls and provide mock responses
export const setupMockApi = () => {
  const originalFetch = window.fetch;
  
  window.fetch = async (url: string | URL | Request, options?: RequestInit): Promise<Response> => {
    const urlString = typeof url === 'string' ? url : url.toString();
    
    // Check if this is an API call we should mock
    if (urlString.includes('/api/v1/')) {
      try {
        let mockData;
        
        if (urlString.includes('/api/v1/agent-posts')) {
          mockData = await mockApiService.getAgentPosts();
        } else if (urlString.includes('/api/v1/claude-live/prod/agents')) {
          mockData = await mockApiService.getAgents();
        } else if (urlString.includes('/api/v1/claude-live/prod/activities')) {
          mockData = await mockApiService.getActivities();
        } else if (urlString.includes('/api/v1/analytics/performance')) {
          const params = new URLSearchParams(urlString.split('?')[1] || '');
          mockData = await mockApiService.getPerformanceAnalytics(params.get('range') || '24h');
        } else if (urlString.includes('/api/v1/analytics/agents')) {
          const params = new URLSearchParams(urlString.split('?')[1] || '');
          mockData = await mockApiService.getAgentAnalytics(params.get('range') || '24h');
        } else if (urlString.includes('/api/v1/analytics/health')) {
          mockData = await mockApiService.getHealthAnalytics();
        } else {
          // For any other API calls, return a generic success response
          mockData = { success: true, data: [], message: 'Mock API response' };
        }
        
        return new Response(JSON.stringify(mockData), {
          status: 200,
          statusText: 'OK',
          headers: {
            'Content-Type': 'application/json',
          },
        });
      } catch (error) {
        return new Response(JSON.stringify({ 
          success: false, 
          error: 'Mock API error',
          message: error instanceof Error ? error.message : 'Unknown error'
        }), {
          status: 500,
          statusText: 'Internal Server Error',
          headers: {
            'Content-Type': 'application/json',
          },
        });
      }
    }
    
    // For non-API calls, use original fetch
    return originalFetch(url, options);
  };
  
  console.log('🎭 Mock API service initialized - intercepting API calls');
};

export default mockApiService;