/**
 * Swarm Coordination System Tests
 * Validates intelligent coordination and parallel development
 * Generated by Testing Validation Agent
 */

const { 
  AdaptiveUISwarmCoordinator,
  SWARM_CONFIG,
  CLAUDABLE_PATTERNS 
} = require('../../src/ui/swarm-coordination');

describe('Adaptive UI Swarm Coordinator', () => {
  let coordinator;
  
  beforeEach(() => {
    coordinator = new AdaptiveUISwarmCoordinator();
  });

  describe('Agent Spawning', () => {
    test('should spawn UI component specialist agent', async () => {
      const agent = await coordinator.spawnAgent(
        'ui-component-specialist',
        'button_component_dev',
        ['react_components', 'professional_styling', 'accessibility']
      );

      expect(agent).toBeDefined();
      expect(agent.type).toBe('ui-component-specialist');
      expect(agent.role).toBe('button_component_dev');
      expect(agent.capabilities).toContain('react_components');
      expect(agent.status).toBe('idle');
    });

    test('should spawn multiple agents with different specializations', async () => {
      const buttonAgent = await coordinator.spawnAgent(
        'ui-component-specialist',
        'button_component_dev',
        ['react_components', 'professional_styling']
      );

      const messageAgent = await coordinator.spawnAgent(
        'ui-component-specialist', 
        'message_list_dev',
        ['virtualization', 'performance_optimization']
      );

      expect(coordinator.agents).toHaveLength(2);
      expect(buttonAgent.specialization).toBe('button');
      expect(messageAgent.specialization).toBe('message-list');
    });
  });

  describe('Task Coordination', () => {
    test('should coordinate parallel development tasks', async () => {
      // Spawn required agents
      await coordinator.spawnAgent('ui-component-specialist', 'button_dev', ['react_components']);
      await coordinator.spawnAgent('ui-component-specialist', 'message_list_dev', ['virtualization']);
      await coordinator.spawnAgent('ui-component-specialist', 'message_input_dev', ['form_handling']);

      const tasks = [
        {
          id: 'task-1',
          component: 'button',
          priority: 'high',
          dependencies: [],
          requirements: {
            claudablePatterns: true,
            regressionSafety: true,
            performanceOptimized: true,
            accessibilityCompliant: true
          }
        },
        {
          id: 'task-2', 
          component: 'message-list',
          priority: 'high',
          dependencies: [],
          requirements: {
            claudablePatterns: true,
            regressionSafety: true,
            performanceOptimized: true,
            accessibilityCompliant: true
          }
        }
      ];

      await expect(coordinator.coordinateParallelDevelopment(tasks)).resolves.toBeUndefined();
    });

    test('should handle task dependencies correctly', async () => {
      const taskWithDependency = {
        id: 'dependent-task',
        component: 'chat-interface', 
        priority: 'medium',
        dependencies: ['button', 'message-list', 'message-input'],
        requirements: {
          claudablePatterns: true,
          regressionSafety: true,
          performanceOptimized: false,
          accessibilityCompliant: true
        }
      };

      // This should handle dependencies properly
      await coordinator.coordinateParallelDevelopment([taskWithDependency]);
      
      // Verify task coordination logic
      expect(coordinator.tasks).toBeDefined();
    });
  });

  describe('Topology Adaptation', () => {
    test('should adapt topology based on workload pattern', () => {
      expect(coordinator.topology).toBe('adaptive');

      coordinator.adaptTopology('high-interdependency');
      expect(coordinator.topology).toBe('hierarchical');

      coordinator.adaptTopology('parallel-intensive');  
      expect(coordinator.topology).toBe('mesh');

      coordinator.adaptTopology('unknown-pattern');
      expect(coordinator.topology).toBe('adaptive');
    });
  });

  describe('Conflict Resolution', () => {
    test('should resolve component conflicts intelligently', async () => {
      const conflicts = [
        {
          component: 'button',
          conflictType: 'styling',
          agents: ['agent-1', 'agent-2'],
          resolution: 'merge'
        }
      ];

      await expect(coordinator.resolveConflicts(conflicts)).resolves.toBeUndefined();
      expect(coordinator.conflictHistory).toHaveLength(1);
    });
  });

  describe('Regression Safety Validation', () => {
    test('should validate regression safety for components', async () => {
      const isButtonSafe = await coordinator.validateRegressionSafety('button');
      const isMessageListSafe = await coordinator.validateRegressionSafety('message-list');
      
      expect(typeof isButtonSafe).toBe('boolean');
      expect(typeof isMessageListSafe).toBe('boolean');
    });
  });

  describe('Performance Tracking', () => {
    test('should track agent performance metrics', () => {
      const agentId = 'test-agent-id';
      const metrics = {
        taskCompletionTime: 1500,
        codeQualityScore: 85,
        regressionTestsPassed: 12,
        userExperienceScore: 90
      };

      coordinator.trackAgentPerformance(agentId, metrics);
      
      const storedMetrics = coordinator.performanceMetrics.get(agentId);
      expect(storedMetrics).toHaveLength(1);
      expect(storedMetrics[0]).toEqual(metrics);
    });
  });
});

describe('Swarm Configuration', () => {
  test('should have proper agent allocation configuration', () => {
    expect(SWARM_CONFIG.maxAgents).toBe(15);
    expect(SWARM_CONFIG.topology).toBe('adaptive');
    
    const totalAgents = Object.values(SWARM_CONFIG.agentAllocation)
      .reduce((sum, count) => sum + count, 0);
    expect(totalAgents).toBe(15);
  });

  test('should have appropriate task priorities', () => {
    expect(SWARM_CONFIG.taskPriorities['regression-safety']).toBe('critical');
    expect(SWARM_CONFIG.taskPriorities['claudable-styling']).toBe('high');
    expect(SWARM_CONFIG.taskPriorities['performance-optimization']).toBe('high');
  });

  test('should have proper coordination protocols', () => {
    expect(SWARM_CONFIG.coordinationProtocols.conflictResolution).toBe('intelligent-merge');
    expect(SWARM_CONFIG.coordinationProtocols.dependencyManagement).toBe('real-time');
    expect(SWARM_CONFIG.coordinationProtocols.qualityAssurance).toBe('continuous');
    expect(SWARM_CONFIG.coordinationProtocols.regressionTesting).toBe('automated');
  });
});

describe('Claudable Patterns', () => {
  test('should have comprehensive design patterns', () => {
    expect(CLAUDABLE_PATTERNS.colors).toBeDefined();
    expect(CLAUDABLE_PATTERNS.spacing).toBeDefined();
    expect(CLAUDABLE_PATTERNS.typography).toBeDefined();
    expect(CLAUDABLE_PATTERNS.interactivity).toBeDefined();
    expect(CLAUDABLE_PATTERNS.layout).toBeDefined();
    expect(CLAUDABLE_PATTERNS.animations).toBeDefined();
  });

  test('should have correct color patterns', () => {
    expect(CLAUDABLE_PATTERNS.colors.primary).toBe('bg-blue-500');
    expect(CLAUDABLE_PATTERNS.colors.secondary).toBe('bg-gray-100 dark:bg-gray-700');
    expect(CLAUDABLE_PATTERNS.colors.error).toBe('bg-red-100 dark:bg-red-900');
    expect(CLAUDABLE_PATTERNS.colors.background).toBe('bg-gray-50 dark:bg-gray-900');
  });

  test('should have proper animation patterns', () => {
    expect(CLAUDABLE_PATTERNS.animations.smooth).toBe('transition-all duration-300');
    expect(CLAUDABLE_PATTERNS.animations.bounce).toBe('animate-bounce');
    expect(CLAUDABLE_PATTERNS.animations.fade).toBe('animate-pulse');
  });

  test('should have accessibility-focused interactivity patterns', () => {
    expect(CLAUDABLE_PATTERNS.interactivity.button).toContain('hover:bg-blue-600');
    expect(CLAUDABLE_PATTERNS.interactivity.input).toContain('focus:ring-2');
    expect(CLAUDABLE_PATTERNS.interactivity.disabled).toContain('disabled:opacity-50');
  });
});

describe('Agent Communication', () => {
  test('should enable cross-agent communication', async () => {
    const coordinator = new AdaptiveUISwarmCoordinator();
    
    const stylingAgent = await coordinator.spawnAgent(
      'styling-integration-specialist',
      'claudable_pattern_analyst',
      ['design_analysis', 'pattern_extraction']
    );

    const componentAgent = await coordinator.spawnAgent(
      'ui-component-specialist',
      'button_component_dev', 
      ['react_components', 'professional_styling']
    );

    expect(coordinator.agents).toHaveLength(2);
    
    // Verify agents can coordinate
    const canCoordinate = coordinator.agents.every(agent => 
      agent.status === 'idle' && agent.capabilities.length > 0
    );
    
    expect(canCoordinate).toBe(true);
  });
});

describe('Integration Testing', () => {
  test('should integrate with existing Claude functionality', async () => {
    const coordinator = new AdaptiveUISwarmCoordinator();
    
    // Test that swarm coordination doesn't break existing functionality
    const regressionSafe = await coordinator.validateRegressionSafety('claude-instance-manager');
    expect(typeof regressionSafe).toBe('boolean');
  });

  test('should maintain performance during swarm operations', () => {
    const coordinator = new AdaptiveUISwarmCoordinator();
    
    const startTime = performance.now();
    
    // Perform multiple swarm operations
    for (let i = 0; i < 10; i++) {
      coordinator.adaptTopology('adaptive');
      coordinator.optimizeTaskAllocation();
    }
    
    const endTime = performance.now();
    const operationTime = endTime - startTime;
    
    // Should complete quickly (under 100ms)
    expect(operationTime).toBeLessThan(100);
  });
});

describe('Error Handling', () => {
  test('should handle agent spawn failures gracefully', async () => {
    const coordinator = new AdaptiveUISwarmCoordinator();
    
    // This should not throw, but handle gracefully
    await expect(coordinator.spawnAgent(
      'invalid-agent-type',
      'test-role',
      ['invalid-capability']
    )).resolves.toBeDefined();
  });

  test('should handle task assignment to non-existent agents', async () => {
    const coordinator = new AdaptiveUISwarmCoordinator();
    
    const task = {
      id: 'test-task',
      component: 'button',
      priority: 'high',
      dependencies: [],
      requirements: {
        claudablePatterns: true,
        regressionSafety: true,
        performanceOptimized: true,
        accessibilityCompliant: true
      }
    };

    await expect(coordinator.assignTask('non-existent-agent', task)).rejects.toThrow();
  });
});