/**
 * London School TDD: Test Helper Utilities
 * 
 * Comprehensive test utilities designed specifically for London School TDD
 * methodology. Provides advanced interaction testing, behavior verification,
 * and mock coordination capabilities.
 * 
 * Focus: Test utilities for behavior-driven testing and mock interactions
 */

import { render, RenderOptions, RenderResult } from '@testing-library/react';
import { ReactElement, ReactNode } from 'react';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// Enhanced render function with common providers
interface CustomRenderOptions extends Omit<RenderOptions, 'wrapper'> {
  initialEntries?: string[];
  queryClient?: QueryClient;
  wrapper?: React.ComponentType<{ children: ReactNode }>;
}

export function renderWithProviders(
  ui: ReactElement,
  options: CustomRenderOptions = {}
): RenderResult {
  const {
    initialEntries = ['/'],
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false }
      }
    }),
    wrapper,
    ...renderOptions
  } = options;

  const AllTheProviders = ({ children }: { children: ReactNode }) => {
    const Wrapper = wrapper || (({ children }: { children: ReactNode }) => <>{children}</>);
    
    return (
      <BrowserRouter>
        <QueryClientProvider client={queryClient}>
          <Wrapper>{children}</Wrapper>
        </QueryClientProvider>
      </BrowserRouter>
    );
  };

  return render(ui, { wrapper: AllTheProviders, ...renderOptions });
}

// Mock data generators for consistent testing
export class MockDataGenerator {
  static generateAgent(overrides: Partial<any> = {}): any {
    return {
      id: 'test-agent-123',
      name: 'Test Agent',
      display_name: 'Test Agent Display',
      description: 'A test agent for unit testing',
      status: 'active',
      capabilities: ['testing', 'validation', 'automation'],
      performance_metrics: {
        success_rate: 94.7,
        average_response_time: 1.5,
        total_tokens_used: 125000,
        uptime_percentage: 99.2
      },
      health_status: {
        cpu_usage: 45.2,
        memory_usage: 67.8,
        response_time: 1.2,
        connection_status: 'connected',
        last_heartbeat: new Date().toISOString()
      },
      created_at: '2024-01-15T10:30:00Z',
      updated_at: new Date().toISOString(),
      last_used: new Date(Date.now() - 3600000).toISOString(),
      avatar_color: '#3B82F6',
      ...overrides
    };
  }

  static generateAgentPost(overrides: Partial<any> = {}): any {
    return {
      id: 'post-test-123',
      title: 'Test Agent Post',
      content: 'This is a test post generated by the test agent for validation purposes.',
      summary: 'Test post summary',
      authorAgent: 'test-agent-123',
      authorAgentName: 'Test Agent',
      publishedAt: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
      updatedAt: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
      status: 'published',
      visibility: 'public',
      tags: ['testing', 'validation', 'automated'],
      category: 'system',
      priority: 'medium',
      metadata: {
        businessImpact: 7.5,
        confidence_score: 0.92,
        processing_time_ms: 85000,
        tokens_used: 5500,
        model_version: 'test-model-v1'
      },
      engagement: {
        views: 156,
        comments: 8,
        shares: 12,
        saves: 15,
        reactions: { like: 25, heart: 8, thumbs_up: 12 }
      },
      ...overrides
    };
  }

  static generateActivity(overrides: Partial<any> = {}): any {
    return {
      id: 'activity-test-123',
      type: 'task_completed',
      description: 'Completed test validation workflow',
      timestamp: new Date(Date.now() - 1800000).toISOString(), // 30 min ago
      agent_id: 'test-agent-123',
      agent_name: 'Test Agent',
      status: 'completed',
      priority: 'medium',
      metadata: {
        duration_ms: 45000,
        tokens_used: 3500,
        error_count: 0,
        retry_count: 0,
        resource_usage: {
          cpu_time_ms: 12000,
          memory_peak_mb: 128,
          disk_io_mb: 5.2,
          network_bytes: 15000
        }
      },
      ...overrides
    };
  }

  static generateSystemMetrics(overrides: Partial<any> = {}): any {
    return {
      timestamp: new Date().toISOString(),
      server_id: 'test-server-001',
      cpu_usage: 42.5,
      memory_usage: 68.3,
      disk_usage: 45.1,
      network_io: {
        bytes_in: 125000,
        bytes_out: 89000,
        packets_in: 1250,
        packets_out: 890
      },
      response_time: 85,
      throughput: 245,
      error_rate: 0.02,
      active_connections: 156,
      queue_depth: 12,
      cache_hit_rate: 0.87,
      ...overrides
    };
  }

  static generateApiResponse<T>(data: T, success = true, overrides: Partial<any> = {}): any {
    return {
      success,
      data,
      timestamp: new Date().toISOString(),
      request_id: 'req-test-' + Math.random().toString(36).substr(2, 9),
      meta: {
        cached: false,
        processing_time_ms: Math.floor(Math.random() * 100) + 50,
        data_source: 'database',
        api_version: '1.0.0'
      },
      ...overrides
    };
  }
}

// Behavior verification utilities
export class BehaviorVerifier {
  static verifyInteractionSequence(
    mocks: Record<string, jest.MockedFunction<any>>,
    expectedSequence: Array<{ mock: string; method?: string; args?: any[] }>
  ): boolean {
    const allCalls: Array<{ mock: string; method?: string; args?: any[]; order: number }> = [];

    Object.entries(mocks).forEach(([mockName, mockFn]) => {
      if (mockFn.mock) {
        mockFn.mock.invocationCallOrder.forEach((order, index) => {
          allCalls.push({
            mock: mockName,
            args: mockFn.mock.calls[index],
            order
          });
        });
      }
    });

    allCalls.sort((a, b) => a.order - b.order);

    if (allCalls.length < expectedSequence.length) {
      return false;
    }

    return expectedSequence.every((expected, index) => {
      const actual = allCalls[index];
      if (!actual || actual.mock !== expected.mock) {
        return false;
      }

      if (expected.args) {
        return JSON.stringify(actual.args) === JSON.stringify(expected.args);
      }

      return true;
    });
  }

  static verifyCollaborationPattern(
    primaryMock: jest.MockedFunction<any>,
    collaboratorMocks: Record<string, jest.MockedFunction<any>>,
    pattern: 'sequential' | 'parallel' | 'conditional'
  ): boolean {
    const primaryCalls = primaryMock.mock.invocationCallOrder;
    const collaboratorCalls = Object.values(collaboratorMocks)
      .flatMap(mock => mock.mock.invocationCallOrder)
      .sort((a, b) => a - b);

    switch (pattern) {
      case 'sequential':
        // Primary mock should be called, then collaborators
        return primaryCalls.length > 0 && 
               collaboratorCalls.length > 0 && 
               Math.max(...primaryCalls) < Math.min(...collaboratorCalls);

      case 'parallel':
        // Primary and collaborator calls should be interleaved
        const allCalls = [...primaryCalls, ...collaboratorCalls].sort((a, b) => a - b);
        const hasInterleaving = allCalls.some((call, index) => {
          if (index === 0) return false;
          const prevCall = allCalls[index - 1];
          const isPrimaryCall = primaryCalls.includes(call);
          const wasPrevPrimary = primaryCalls.includes(prevCall);
          return isPrimaryCall !== wasPrevPrimary;
        });
        return hasInterleaving;

      case 'conditional':
        // Collaborators should only be called if primary was called
        return collaboratorCalls.length === 0 || primaryCalls.length > 0;

      default:
        return false;
    }
  }

  static verifyErrorHandling(
    errorMock: jest.MockedFunction<any>,
    recoveryMocks: Record<string, jest.MockedFunction<any>>
  ): boolean {
    if (errorMock.mock.calls.length === 0) {
      // No errors, recovery mocks shouldn't be called
      return Object.values(recoveryMocks).every(mock => mock.mock.calls.length === 0);
    }

    // Errors occurred, at least one recovery mock should be called
    return Object.values(recoveryMocks).some(mock => mock.mock.calls.length > 0);
  }

  static verifyResourceCleanup(
    setupMocks: Record<string, jest.MockedFunction<any>>,
    cleanupMocks: Record<string, jest.MockedFunction<any>>
  ): boolean {
    // For each setup call, there should be a corresponding cleanup call
    const setupCalls = Object.values(setupMocks)
      .reduce((total, mock) => total + mock.mock.calls.length, 0);
    const cleanupCalls = Object.values(cleanupMocks)
      .reduce((total, mock) => total + mock.mock.calls.length, 0);

    return setupCalls <= cleanupCalls;
  }
}

// Performance testing utilities
export class PerformanceTestHelper {
  static async measureAsyncOperation<T>(
    operation: () => Promise<T>,
    maxDuration = 1000
  ): Promise<{ result: T; duration: number; withinLimit: boolean }> {
    const startTime = performance.now();
    const result = await operation();
    const endTime = performance.now();
    const duration = endTime - startTime;

    return {
      result,
      duration,
      withinLimit: duration <= maxDuration
    };
  }

  static measureRenderPerformance(
    renderFn: () => RenderResult,
    maxRenderTime = 16.67 // 60fps target
  ): { renderTime: number; withinLimit: boolean; result: RenderResult } {
    const startTime = performance.now();
    const result = renderFn();
    const endTime = performance.now();
    const renderTime = endTime - startTime;

    return {
      renderTime,
      withinLimit: renderTime <= maxRenderTime,
      result
    };
  }

  static createPerformanceBudget(limits: {
    initialRender?: number;
    dataLoad?: number;
    userInteraction?: number;
    navigation?: number;
  }) {
    return {
      checkBudget(operation: keyof typeof limits, duration: number): boolean {
        const limit = limits[operation];
        return limit ? duration <= limit : true;
      },
      
      getBudgetStatus(measurements: Record<keyof typeof limits, number>) {
        return Object.entries(measurements).reduce((status, [operation, duration]) => {
          const limit = limits[operation as keyof typeof limits];
          status[operation] = {
            duration,
            limit: limit || Infinity,
            withinBudget: limit ? duration <= limit : true
          };
          return status;
        }, {} as Record<string, { duration: number; limit: number; withinBudget: boolean }>);
      }
    };
  }
}

// Accessibility testing helpers
export class AccessibilityTestHelper {
  static createARIAAttributeChecker() {
    return {
      hasRequiredARIA(element: Element, requiredAttributes: string[]): boolean {
        return requiredAttributes.every(attr => element.hasAttribute(attr));
      },

      hasValidARIAValues(element: Element, attributeValidations: Record<string, string[]>): boolean {
        return Object.entries(attributeValidations).every(([attr, validValues]) => {
          const value = element.getAttribute(attr);
          return value ? validValues.includes(value) : true;
        });
      },

      checkARIALabelledBy(element: Element): boolean {
        const labelledBy = element.getAttribute('aria-labelledby');
        if (labelledBy) {
          return labelledBy.split(' ').every(id => document.getElementById(id) !== null);
        }
        return element.hasAttribute('aria-label') || element.hasAttribute('title');
      }
    };
  }

  static createKeyboardNavigationTester() {
    return {
      isFocusable(element: Element): boolean {
        const focusableSelectors = [
          'button:not([disabled])',
          'input:not([disabled])',
          'select:not([disabled])',
          'textarea:not([disabled])',
          'a[href]',
          '[tabindex]:not([tabindex="-1"])'
        ];

        return focusableSelectors.some(selector => element.matches(selector));
      },

      hasLogicalTabOrder(container: Element): boolean {
        const focusableElements = Array.from(
          container.querySelectorAll([
            'button:not([disabled])',
            'input:not([disabled])',
            'select:not([disabled])',
            'textarea:not([disabled])',
            'a[href]',
            '[tabindex]:not([tabindex="-1"])'
          ].join(', '))
        );

        const tabIndexes = focusableElements.map(el => {
          const tabIndex = el.getAttribute('tabindex');
          return tabIndex ? parseInt(tabIndex, 10) : 0;
        });

        // Check if tab order is logical (ascending or all zeros)
        for (let i = 1; i < tabIndexes.length; i++) {
          if (tabIndexes[i] !== 0 && tabIndexes[i - 1] !== 0) {
            if (tabIndexes[i] < tabIndexes[i - 1]) {
              return false;
            }
          }
        }

        return true;
      }
    };
  }

  static createColorContrastChecker() {
    return {
      calculateContrast(foreground: string, background: string): number {
        // Simplified contrast calculation for testing
        const fgLum = this.getLuminance(foreground);
        const bgLum = this.getLuminance(background);
        const lighter = Math.max(fgLum, bgLum);
        const darker = Math.min(fgLum, bgLum);
        return (lighter + 0.05) / (darker + 0.05);
      },

      getLuminance(color: string): number {
        // Simplified luminance calculation
        const rgb = this.hexToRgb(color);
        if (!rgb) return 0;
        
        const [r, g, b] = [rgb.r, rgb.g, rgb.b].map(c => {
          c = c / 255;
          return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
        });
        
        return 0.2126 * r + 0.7152 * g + 0.0722 * b;
      },

      hexToRgb(hex: string): { r: number; g: number; b: number } | null {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result ? {
          r: parseInt(result[1], 16),
          g: parseInt(result[2], 16),
          b: parseInt(result[3], 16)
        } : null;
      },

      meetsWCAGAA(contrast: number): boolean {
        return contrast >= 4.5;
      },

      meetsWCAGAAA(contrast: number): boolean {
        return contrast >= 7;
      }
    };
  }
}

// Test scenario builders
export class TestScenarioBuilder {
  static createDataLoadingScenario(config: {
    mockData: any;
    loadingTime?: number;
    shouldFail?: boolean;
    errorMessage?: string;
  }) {
    return {
      mockApiResponse: config.shouldFail 
        ? Promise.reject(new Error(config.errorMessage || 'Loading failed'))
        : new Promise(resolve => 
            setTimeout(() => resolve(config.mockData), config.loadingTime || 0)
          ),
      
      expectedLoadingStates: config.shouldFail
        ? ['loading', 'error']
        : ['loading', 'success'],
      
      verifyLoadingSequence(loadingStates: string[]): boolean {
        return JSON.stringify(loadingStates) === JSON.stringify(this.expectedLoadingStates);
      }
    };
  }

  static createUserInteractionScenario(config: {
    action: string;
    target: string;
    expectedBehaviors: string[];
    shouldSucceed?: boolean;
  }) {
    return {
      action: config.action,
      target: config.target,
      expectedBehaviors: config.expectedBehaviors,
      shouldSucceed: config.shouldSucceed ?? true,
      
      verifyBehaviorSequence(actualBehaviors: string[]): boolean {
        return config.expectedBehaviors.every(expected => 
          actualBehaviors.includes(expected)
        );
      }
    };
  }

  static createErrorRecoveryScenario(config: {
    errorType: string;
    recoveryActions: string[];
    fallbackData?: any;
  }) {
    return {
      errorType: config.errorType,
      recoveryActions: config.recoveryActions,
      fallbackData: config.fallbackData,
      
      simulateError(): Error {
        return new Error(`Simulated ${config.errorType} error`);
      },
      
      verifyRecoverySequence(actualActions: string[]): boolean {
        return config.recoveryActions.every(expected =>
          actualActions.includes(expected)
        );
      }
    };
  }
}

// Export all utilities
export * from './swarm-mock-coordination';