/**
 * Hierarchical Swarm Test Suite - TDD London School Implementation
 * Tests for hybrid solution: Option A (fetchInstances callbacks) + Option C (terminal input echo via SSE)
 * Generated by: TDD-London-Swarm Agent
 * Mission: Validate instance list refresh + terminal input/output cycle
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ClaudeInstanceManager from '../../src/components/ClaudeInstanceManager';
import { useHTTPSSE } from '../../src/hooks/useHTTPSSE';

// Mock dependencies
vi.mock('../../src/hooks/useHTTPSSE');
vi.mock('../../src/utils/nld-ui-capture', () => ({
  nldCapture: {
    captureCommunicationBreakdown: vi.fn(),
    captureInstanceCreationFailure: vi.fn()
  }
}));

// TDD Test Suite for Instance List Refresh (Option A)
describe('Hierarchical Swarm: Instance List Refresh Functionality', () => {
  let queryClient: QueryClient;
  let mockSSE: any;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false }
      }
    });

    mockSSE = {
      socket: {},
      isConnected: true,
      connectionError: null,
      connectSSE: vi.fn(),
      startPolling: vi.fn(),
      disconnectFromInstance: vi.fn(),
      on: vi.fn(),
      off: vi.fn(),
      emit: vi.fn()
    };

    (useHTTPSSE as any).mockReturnValue(mockSSE);
    
    // Mock fetch responses
    global.fetch = vi.fn();
  });

  it('should call fetchInstances after successful instance creation (Option A - Critical Fix)', async () => {
    // Arrange - Mock successful instance creation
    (global.fetch as any)
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          success: true,
          instances: []
        })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          success: true,
          instanceId: 'claude-1234',
          instance: { id: 'claude-1234', name: 'prod/claude', status: 'starting' }
        })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          success: true,
          instances: [{
            id: 'claude-1234',
            name: 'prod/claude',
            status: 'running',
            pid: 1234
          }]
        })
      });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    // Act - Click the prod/claude button
    const prodButton = screen.getByText('🚀 prod/claude');
    fireEvent.click(prodButton);

    // Assert - fetchInstances should be called after creation
    await waitFor(() => {
      expect(global.fetch).toHaveBeenCalledWith('http://localhost:3000/api/claude/instances');
      expect(global.fetch).toHaveBeenCalledWith('http://localhost:3000/api/claude/instances', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          command: ['claude'],
          workingDirectory: '/workspaces/agent-feed/prod'
        })
      });
      // Critical: fetchInstances called again after creation
      expect(global.fetch).toHaveBeenCalledTimes(3); // Initial + Create + Refresh
    });
  });

  it('should refresh instance list and show new instance immediately', async () => {
    // Arrange - Mock instance creation flow
    let fetchCallCount = 0;
    (global.fetch as any).mockImplementation((url: string, options?: any) => {
      if (url.includes('/api/claude/instances') && !options?.method) {
        // GET /api/claude/instances calls
        fetchCallCount++;
        if (fetchCallCount === 1) {
          return Promise.resolve({
            ok: true,
            json: () => Promise.resolve({ success: true, instances: [] })
          });
        } else {
          return Promise.resolve({
            ok: true,
            json: () => Promise.resolve({
              success: true,
              instances: [{
                id: 'claude-1234',
                name: 'prod/claude',
                status: 'running',
                pid: 1234
              }]
            })
          });
        }
      } else if (options?.method === 'POST') {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            success: true,
            instanceId: 'claude-1234'
          })
        });
      }
    });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    // Act
    fireEvent.click(screen.getByText('🚀 prod/claude'));

    // Assert - Instance appears in list
    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
    });
  });

  it('should test all 4 buttons create instances with proper fetchInstances callbacks', async () => {
    const mockInstances: any[] = [];
    let instanceCount = 0;

    (global.fetch as any).mockImplementation((url: string, options?: any) => {
      if (options?.method === 'POST') {
        instanceCount++;
        const newInstance = {
          id: `claude-${1000 + instanceCount}`,
          name: `Instance ${instanceCount}`,
          status: 'running',
          pid: 1000 + instanceCount
        };
        mockInstances.push(newInstance);
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            success: true,
            instanceId: newInstance.id
          })
        });
      } else {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            success: true,
            instances: [...mockInstances]
          })
        });
      }
    });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    // Test all 4 buttons
    const buttons = [
      '🚀 prod/claude',
      '⚡ skip-permissions',
      '⚡ skip-permissions -c',
      '↻ skip-permissions --resume'
    ];

    for (const buttonText of buttons) {
      fireEvent.click(screen.getByText(buttonText));
      await waitFor(() => {
        expect(mockInstances.length).toBeGreaterThan(0);
      });
    }

    // All instances should be visible
    await waitFor(() => {
      expect(screen.getAllByText(/Instance \d/).length).toBe(4);
    });
  });
});

// TDD Test Suite for Terminal Input Echo (Option C)
describe('Hierarchical Swarm: Terminal Input Echo Functionality', () => {
  let queryClient: QueryClient;
  let mockSSE: any;
  let mockOnHandlers: { [key: string]: Function } = {};

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false }
      }
    });

    mockOnHandlers = {};
    
    mockSSE = {
      socket: {},
      isConnected: true,
      connectionError: null,
      connectSSE: vi.fn(),
      startPolling: vi.fn(),
      disconnectFromInstance: vi.fn(),
      on: vi.fn((event: string, handler: Function) => {
        mockOnHandlers[event] = handler;
      }),
      off: vi.fn(),
      emit: vi.fn()
    };

    (useHTTPSSE as any).mockReturnValue(mockSSE);
    
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({
        success: true,
        instances: [{
          id: 'claude-1234',
          name: 'prod/claude',
          status: 'running',
          pid: 1234
        }]
      })
    });
  });

  it('should handle terminal input echo events from SSE (Option C - Critical Fix)', async () => {
    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    // Wait for instance to load and select it
    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
    });

    fireEvent.click(screen.getByText('prod/claude'));

    // Simulate input_echo event from backend SSE
    const inputEchoData = {
      type: 'input_echo',
      instanceId: 'claude-1234',
      data: 'hello',
      timestamp: new Date().toISOString()
    };

    // Trigger the echo event
    if (mockOnHandlers['terminal:output']) {
      mockOnHandlers['terminal:output']({
        output: inputEchoData.data,
        instanceId: inputEchoData.instanceId
      });
    }

    // Assert echo appears in output
    await waitFor(() => {
      const outputArea = screen.getByText(/hello/);
      expect(outputArea).toBeInTheDocument();
    });
  });

  it('should send terminal input and receive echo response', async () => {
    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
    });

    fireEvent.click(screen.getByText('prod/claude'));

    const input = screen.getByPlaceholderText('Type command and press Enter...');
    
    // Type "hello" 
    fireEvent.change(input, { target: { value: 'hello' } });
    fireEvent.keyPress(input, { key: 'Enter', code: 'Enter', charCode: 13 });

    // Should emit terminal:input
    expect(mockSSE.emit).toHaveBeenCalledWith('terminal:input', {
      input: 'hello\n',
      instanceId: 'claude-1234'
    });

    // Simulate backend response with echo
    if (mockOnHandlers['terminal:output']) {
      mockOnHandlers['terminal:output']({
        output: 'hello\n$ ',
        instanceId: 'claude-1234'
      });
    }

    await waitFor(() => {
      expect(screen.getByText(/hello/)).toBeInTheDocument();
    });
  });

  it('should handle command responses after input echo', async () => {
    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    await waitFor(() => {
      fireEvent.click(screen.getByText('prod/claude'));
    });

    // Send "ls" command
    const input = screen.getByPlaceholderText('Type command and press Enter...');
    fireEvent.change(input, { target: { value: 'ls' } });
    fireEvent.keyPress(input, { key: 'Enter' });

    // Simulate backend processing: input echo + command response
    if (mockOnHandlers['terminal:output']) {
      // Echo
      mockOnHandlers['terminal:output']({
        output: 'ls',
        instanceId: 'claude-1234'
      });
      
      // Response
      mockOnHandlers['terminal:output']({
        output: '\npackage.json\nsrc\nREADME.md\n$ ',
        instanceId: 'claude-1234'
      });
    }

    await waitFor(() => {
      expect(screen.getByText(/package.json/)).toBeInTheDocument();
    });
  });
});

// Integration Tests - Hybrid Solution (Option A + C)
describe('Hierarchical Swarm: Hybrid Solution Integration Tests', () => {
  let queryClient: QueryClient;
  let mockSSE: any;
  let mockOnHandlers: { [key: string]: Function } = {};

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false }
      }
    });

    mockOnHandlers = {};
    mockSSE = {
      socket: {},
      isConnected: true,
      connectionError: null,
      connectSSE: vi.fn(),
      startPolling: vi.fn(),
      disconnectFromInstance: vi.fn(),
      on: vi.fn((event: string, handler: Function) => {
        mockOnHandlers[event] = handler;
      }),
      off: vi.fn(),
      emit: vi.fn()
    };

    (useHTTPSSE as any).mockReturnValue(mockSSE);
  });

  it('should complete full workflow: button click → instance appears → terminal input → echo response', async () => {
    // Mock API responses
    let instanceCreated = false;
    (global.fetch as any).mockImplementation((url: string, options?: any) => {
      if (options?.method === 'POST') {
        instanceCreated = true;
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            success: true,
            instanceId: 'claude-1234'
          })
        });
      } else {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            success: true,
            instances: instanceCreated ? [{
              id: 'claude-1234',
              name: 'prod/claude',
              status: 'running',
              pid: 1234
            }] : []
          })
        });
      }
    });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    // Step 1: Click button → Instance should appear (Option A)
    fireEvent.click(screen.getByText('🚀 prod/claude'));
    
    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
    });

    // Step 2: Select instance and send input
    fireEvent.click(screen.getByText('prod/claude'));
    
    const input = screen.getByPlaceholderText('Type command and press Enter...');
    fireEvent.change(input, { target: { value: 'hello' } });
    fireEvent.keyPress(input, { key: 'Enter' });

    // Step 3: Verify terminal input was sent
    expect(mockSSE.emit).toHaveBeenCalledWith('terminal:input', {
      input: 'hello\n',
      instanceId: 'claude-1234'
    });

    // Step 4: Simulate backend SSE response (Option C)
    if (mockOnHandlers['terminal:output']) {
      mockOnHandlers['terminal:output']({
        output: 'hello\n$ ',
        instanceId: 'claude-1234'
      });
    }

    // Step 5: Verify echo appears
    await waitFor(() => {
      expect(screen.getByText(/hello/)).toBeInTheDocument();
    });

    // Success: Complete workflow validated!
  });

  it('should handle multiple instances with independent terminal sessions', async () => {
    const instances = [
      { id: 'claude-1234', name: 'prod/claude', status: 'running', pid: 1234 },
      { id: 'claude-5678', name: 'skip-permissions', status: 'running', pid: 5678 }
    ];

    (global.fetch as any).mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ success: true, instances })
    });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
      expect(screen.getByText('skip-permissions')).toBeInTheDocument();
    });

    // Test both instances independently
    fireEvent.click(screen.getByText('prod/claude'));
    
    if (mockOnHandlers['terminal:output']) {
      mockOnHandlers['terminal:output']({
        output: 'Instance 1 output',
        instanceId: 'claude-1234'
      });
    }

    await waitFor(() => {
      expect(screen.getByText(/Instance 1 output/)).toBeInTheDocument();
    });

    fireEvent.click(screen.getByText('skip-permissions'));
    
    if (mockOnHandlers['terminal:output']) {
      mockOnHandlers['terminal:output']({
        output: 'Instance 2 output',
        instanceId: 'claude-5678'
      });
    }

    await waitFor(() => {
      expect(screen.getByText(/Instance 2 output/)).toBeInTheDocument();
    });
  });
});

// Performance Tests
describe('Hierarchical Swarm: Performance Validation', () => {
  it('should complete instance creation and refresh within 2 seconds', async () => {
    const startTime = performance.now();
    
    const queryClient = new QueryClient();
    const mockSSE = {
      socket: {},
      isConnected: true,
      connectionError: null,
      connectSSE: vi.fn(),
      startPolling: vi.fn(),
      disconnectFromInstance: vi.fn(),
      on: vi.fn(),
      off: vi.fn(),
      emit: vi.fn()
    };

    (useHTTPSSE as any).mockReturnValue(mockSSE);
    
    (global.fetch as any)
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ success: true, instances: [] })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ success: true, instanceId: 'claude-1234' })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          success: true,
          instances: [{ id: 'claude-1234', name: 'prod/claude', status: 'running' }]
        })
      });

    render(
      <QueryClientProvider client={queryClient}>
        <ClaudeInstanceManager />
      </QueryClientProvider>
    );

    fireEvent.click(screen.getByText('🚀 prod/claude'));

    await waitFor(() => {
      expect(screen.getByText('prod/claude')).toBeInTheDocument();
    });

    const endTime = performance.now();
    expect(endTime - startTime).toBeLessThan(2000); // Under 2 seconds
  });
});